metro_stations = {
"Purple Line": [
    "Challaghatta",
    "Kengeri",
    "Kengeri Bus Terminal",
    "Pattanagere",
    "Jnanabharathi",
    "Rajarajeshwari Nagar",
    "Pantharapalya - Nayandahalli",
    "Mysuru Road",
    "Deepanjali Nagar",
    "Attiguppe",
    "Vijayanagar",
    "Sri Balagangadharanatha Swamiji Stn., Hosahalli",
    "Magadi Road",
    "Krantiveera Sangolli Rayanna Railway Station",
    "Nadaprabhu Kempegowda Stn., Majestic",
    "Sir M. Visvesvaraya",
    "Vidhana Soudha",
    "Cubbon Park",
    "Mahatma Gandhi Road",
    "Trinity",
    "Halasuru",
    "Indiranagar",
    "Swami Vivekananda Road",
    "Baiyappanahalli",
    "Benniganahalli",
    "Krishnarajapura",
    "Singayyanapalya",
    "Garudacharpalya",
    "Hoodi",
    "Seetharamapalya",
    "Kundalahalli",
    "Nallurhalli",
    "Sri Sathya Sai Hospital",
    "Pattandur Agrahara",
    "Kadugodi Tree Park",
    "Hopefarm Channasandra",
    "Whitefield (Kadugodi)"
],
"Green Line": [
    "Madavara",
    "Chikkabidarakallu",
    "Manjunath Nagar",
    "Nagasandra",
    "Dasarahalli",
    "Jalahalli",
    "Peenya Industry",
    "Peenya",
    "Goraguntepalya",
    "Yeshwanthpur",
    "Sandal Soap Factory",
    "Mahalakshmi",
    "Rajajinagar",
    "Kuvempu Road",
    "Srirampura",
    "Mantri Square Sampige Road",
    "Nadaprabhu Kempegowda Stn., Majestic",
    "Chickpete",
    "Krishna Rajendra Market",
    "National College",
    "Lalbagh",
    "South End Circle",
    "Jayanagar",
    "Rashtreeya Vidyalaya Road",
    "Banashankari",
    "Jaya Prakash Nagar",
    "Yelachenahalli",
    "Konankunte Cross",
    "Doddakallasandra",
    "Vajarahalli",
    "Thalaghattapura",
    "Silk Institute"
],
"Yellow Line": [
    "Rashtreeya Vidyalaya Road",
    "Ragigudda",
    "Jayadeva Hospital",
    "BTM Layout",
    "Central Silk Board",
    "Bommanahalli",
    "Hongasandra",
    "Kudlu Gate",
    "Singasandra",
    "Hosa Road",
    "Beratena Agrahara",
    "Electronic City",
    "Infosys Foundation Konappana Agrahara",
    "Huskur Road",
    "Biocon Hebbagodi",
    "Delta Electronics Bommasandra"
],
"Blue Line (TBC)": [
        'KIAL Terminals (TBC)',
        'Airport City (TBC)',
        'Doddajala (TBC)',
        'Bettahalasuru (TBC)',
        'Bagalur Cross (TBC)',
        'Yelahanka (TBC)',
        'Jakkur Cross (TBC)',
        'Kodigehalli (TBC)',
        'Hebbala (TBC)',
        'Kempapura (TBC)',
        'Veerannapalya (TBC)',
        'Nagawara (TBC)',
        'HBR Layout (TBC)',
        'Kalyan Nagar (TBC)',
        'HRBR Layout (TBC)',
        'Horamavu (TBC)',
        'Kasturinagara (TBC)',
        'Krishnarajapura',
        'Saraswathi Nagar (TBC)',
        'DRDO Sports Complex (TBC)',
        'Doddanekundi (TBC)',
        'ISRO (TBC)',
        'Marathahalli (TBC)',
        'Kodibeesanahalli (TBC)',
        'Kadubeesanahalli (TBC)',
        'Bellandur (TBC)',
        'Ibbaluru (TBC)',
        'Agara (TBC)',
        'HSR Layout (TBC)',
        'Central Silk Board'
],
"Pink Line (TBC)": [
        'Kalena Agrahara (TBC)',
        'Hulimavu (TBC)',
        'IIMB (TBC)',
        'JP Nagar 4th Phase (TBC)',
        'Jayadeva Hospital',
        'Tavarekere (TBC)',
        'Dairy Circle (TBC)',
        'Lakkasandra (TBC)',
        'Langford Town (TBC)',
        'National Military School (TBC)',
        'Mahatma Gandhi Road',
        'Shivajinagar (TBC)',
        'Cantonment Railway Station (TBC)',
        'Pottery Town (TBC)',
        'Tannery Road (TBC)',
        'Venkateshpura (TBC)',
        'Kadugundanahalli (TBC)',
        'Nagawara (TBC)'
],
"Orange Line (TBC)": [
        'JP Nagar 4th Phase (TBC)',
        'JP Nagar 5th Phase (TBC)',
        'Jaya Prakash Nagar',
        'Kadirenahalli Cross (TBC)',
        'Kamakya Bus Depot (TBC)',
        'Hosakerehalli Cross (TBC)',
        'PES Institute of Technology (TBC)',
        'Mysuru Road',
        'Nagarabhavi Circle (TBC)',
        'Vinayaka Layout (TBC)',
        'Dr. Ambedkar Institute of Technology (TBC)',
        'Nagarbhavi BDA Complex (TBC)',
        'Sumanahalli Cross (TBC)',
        'Chowdeshwari Nagara (TBC)',
        'Freedom Fighters Cross (TBC)',
        'Kanteerava Studio (TBC)',
        'Peenya',
        'Bahubali Nagara (TBC)',
        'BEL Circle (TBC)',
        'Patelappa Layout (TBC)',
        'Hebbala (TBC)',
        'Kempapura (TBC)'
],
"Grey Line (TBC)": [
        'Sri Balagangadharanatha Swamiji Stn., Hosahalli',
        'KHB Colony (TBC)',
        'Vinayaka Nagara (TBC)',
        'Sumanahalli Cross (TBC)',
        'Sunkadakatte (TBC)',
        'Herohalli (TBC)',
        'Byadarahalli (TBC)',
        'Forest Gate (TBC)',
        'Kadabagere (TBC)'
]}

interchange_stations = {
    'Nadaprabhu Kempegowda Stn., Majestic': ['Purple Line', 'Green Line'],
    'Mahatma Gandhi Road': ['Purple Line', 'Pink Line (TBC)'],
    'Krishnarajapura': ['Purple Line', 'Blue Line (TBC)'],
    'Central Silk Board': ['Blue Line (TBC)', 'Yellow Line (TBC)'],
    'Nagawara (TBC)': ['Blue Line (TBC)', 'Pink Line (TBC)'],
    'Kempapura (TBC)': ['Blue Line (TBC)', 'Orange Line (TBC)'],
    'Jayadeva Hospital': ['Yellow Line (TBC)', 'Pink Line (TBC)'],
    'Rashtreeya Vidyalaya Road': ['Green Line (TBC)', 'Yellow Line (TBC)'],
    'JP Nagar 4th Phase (TBC)': ['Pink Line', 'Orange Line (TBC)'],
    'Jaya Prakash Nagar': ['Green Line', 'Orange Line (TBC)'],
    'Mysuru Road': ['Purple Line', 'Orange Line (TBC)'],
    'Peenya': ['Green Line', 'Orange Line (TBC)'],
    'Sri Balagangadharanatha Swamiji Stn., Hosahalli': ['Purple Line', 'Grey Line (TBC)'],
    'Sumanahalli Cross (TBC)': ['Orange Line (TBC)', 'Grey Line (TBC)']
}
