metro_stations = {
    'purple_line': [
        'Challaghatta',
        'Kengeri',
        'Kengeri Bus Terminal',
        'Pattanagere',
        'Jnanabharathi',
        'Rajarajeshwari Nagar',
        'Pantharapalya - Nayandahalli',
        'Mysuru Road',
        'Deepanjali Nagar',
        'Attiguppe',
        'Vijayanagar',
        'Sri Balagangadharanatha Swamiji Stn., Hosahalli',
        'Magadi Road',
        'Krantiveera Sangolli Rayanna Railway Station',
        'Nadaprabhu Kempegowda Stn., Majestic',
        'Sir M. Visveshwaraya',
        'Vidhana Soudha',
        'Cubbon Park',
        'Mahatma Gandhi Road',
        'Trinity',
        'Halasuru',
        'Indiranagar',
        'Swami Vivekananda Road',
        'Baiyappanahalli',
        'Benniganahalli',
        'Krishnarajapura',
        'Singayyanapalya',
        'Garudacharapalya',
        'Hoodi',
        'Seetharamapalya',
        'Kundalahalli',
        'Nallurhalli',
        'Sri Sathya Sai Hospital',
        'Pattandur Agrahara',
        'Kadugodi Tree Park',
        'Hopefarm Channasandra',
        'Whitefield (Kadugodi)'
    ],
    'green_line': [
        'Silk Institute',
        'Thalaghattapura',
        'Vajarahalli',
        'Doddakallasandra',
        'Konankunte Cross',
        'Yelachenahalli',
        'Jaya Prakash Nagar',
        'Banashankari',
        'Rashtreeya Vidyalaya Road',
        'Jayanagar',
        'South End Circle',
        'Lalbagh',
        'National College',
        'Krishna Rajendra Market',
        'Chickpete',
        'Nadaprabhu Kempegowda Stn., Majestic',
        'Sampige Road',
        'Srirampura',
        'Kuvempu Road',
        'Rajajinagar',
        'Mahalakshmi',
        'Sandal Soap Factory',
        'Yeshwanthpur',
        'Goraguntepalya',
        'Peenya',
        'Peenya Industry',
        'Jalahalli',
        'Dasarahalli',
        'Nagasandra',
        'Manjunath Nagar',
        'Chikkabidarakallu',
        'Madavara'
    ],
    'blue_line': [
        'KIAL Terminals (TBC)',
        'Airport City (TBC)',
        'Doddajala (TBC)',
        'Bettahalasuru (TBC)',
        'Bagalur Cross (TBC)',
        'Yelahanka (TBC)',
        'Jakkur Cross (TBC)',
        'Kodigehalli (TBC)',
        'Hebbala (TBC)',
        'Kempapura (TBC)',
        'Veerannapalya (TBC)',
        'Nagawara (TBC)',
        'HBR Layout (TBC)',
        'Kalyan Nagar (TBC)',
        'HRBR Layout (TBC)',
        'Horamavu (TBC)',
        'Kasturinagara (TBC)',
        'Krishnarajapura',
        'Saraswathi Nagar (TBC)',
        'DRDO Sports Complex (TBC)',
        'Doddanekundi (TBC)',
        'ISRO (TBC)',
        'Marathahalli (TBC)',
        'Kodibeesanahalli (TBC)',
        'Kadubeesanahalli (TBC)',
        'Bellandur (TBC)',
        'Ibbaluru (TBC)',
        'Agara (TBC)',
        'HSR Layout (TBC)',
        'Central Silk Board (TBC)'
    ],
    'yellow_line': [
        'Rashtreeya Vidyalaya Road',
        'Ragigudda (TBC)',
        'Jayadeva Hospital (TBC)',
        'BTM Layout (TBC)',
        'Central Silk Board (TBC)',
        'Bommanahalli (TBC)',
        'Hongasandra (TBC)',
        'Kudlu Gate (TBC)',
        'Singasandra (TBC)',
        'Hosa Road (TBC)',
        'Beratena Agrahara (TBC)',
        'Konappana Agrahara (TBC)',
        'Electronic City (TBC)',
        'Huskur Road (TBC)',
        'Hebbagodi (TBC)',
        'Bommasandra (TBC)'
    ],
    'pink_line': [
        'Kalena Agrahara (TBC)',
        'Hulimavu (TBC)',
        'IIMB (TBC)',
        'JP Nagar 4th Phase (TBC)',
        'Jayadeva Hospital (TBC)',
        'Tavarekere (TBC)',
        'Dairy Circle (TBC)',
        'Lakkasandra (TBC)',
        'Langford Town (TBC)',
        'National Military School (TBC)',
        'Mahatma Gandhi Road',
        'Shivajinagar (TBC)',
        'Cantonment Railway Station (TBC)',
        'Pottery Town (TBC)',
        'Tannery Road (TBC)',
        'Venkateshpura (TBC)',
        'Kadugundanahalli (TBC)',
        'Nagawara (TBC)'
    ],
    'orange_line': [
        'JP Nagar 4th Phase (TBC)',
        'JP Nagar 5th Phase (TBC)',
        'Jaya Prakash Nagar',
        'Kadirenahalli Cross (TBC)',
        'Kamakya Bus Depot (TBC)',
        'Hosakerehalli Cross (TBC)',
        'PES Institute of Technology (TBC)',
        'Mysuru Road',
        'Nagarabhavi Circle (TBC)',
        'Vinayaka Layout (TBC)',
        'Dr. Ambedkar Institute of Technology (TBC)',
        'Nagarbhavi BDA Complex (TBC)',
        'Sumanahalli Cross (TBC)',
        'Chowdeshwari Nagara (TBC)',
        'Freedom Fighters Cross (TBC)',
        'Kanteerava Studio (TBC)',
        'Peenya',
        'Bahubali Nagara (TBC)',
        'BEL Circle (TBC)',
        'Patelappa Layout (TBC)',
        'Hebbala (TBC)',
        'Kempapura (TBC)'
    ],
    'grey_line': [
        'Sri Balagangadharanatha Swamiji Stn., Hosahalli',
        'KHB Colony (TBC)',
        'Vinayaka Nagara (TBC)',
        'Sumanahalli Cross (TBC)',
        'Sunkadakatte (TBC)',
        'Herohalli (TBC)',
        'Byadarahalli (TBC)',
        'Forest Gate (TBC)',
        'Kadabagere (TBC)'
    ],
    'interchange_stations': {
        'Nadaprabhu Kempegowda Stn., Majestic': ['purple_line', 'green_line'],
        'Chickpete': ['purple_line', 'green_line'],
        'Mahatma Gandhi Road': ['purple_line', 'pink_line'],
        'Krishnarajapura': ['purple_line', 'blue_line'],
        'Central Silk Board (TBC)': ['blue_line', 'yellow_line'],
        'Nagawara (TBC)': ['blue_line', 'pink_line'],
        'Kempapura (TBC)': ['blue_line', 'orange_line'],
        'Jayadeva Hospital (TBC)': ['yellow_line', 'pink_line'],
        'Rashtreeya Vidyalaya Road': ['green_line', 'yellow_line'],
        'JP Nagar 4th Phase (TBC)': ['pink_line', 'orange_line'],
        'Jaya Prakash Nagar': ['green_line', 'orange_line'],
        'Mysuru Road': ['purple_line', 'orange_line'],
        'Peenya': ['green_line', 'orange_line'],
        'Sri Balagangadharanatha Swamiji Stn., Hosahalli': ['purple_line', 'grey_line'],
        'Sumanahalli Cross (TBC)': ['orange_line', 'grey_line']
    }
}
